import type { ContributorPermission, ContributorRole } from "./types";

export const CONTRIBUTOR_PERMISSIONS: Record<ContributorRole, readonly ContributorPermission[]> = {
  READER: [
    "contribution:read",
    "community:vote",
    "profile:view:any",
  ],
  CONTRIBUTOR: [
    "contribution:create",
    "contribution:read",
    "contribution:edit:own",
    "contribution:submit",
    "contribution:fork",
    "contribution:collaborate",
    "evidence:upload",
    "citation:add",
    "community:vote",
    "community:note",
    "investigation:view",
    "profile:edit:own",
    "profile:view:any",
  ],
  RESEARCHER: [
    "contribution:create",
    "contribution:read",
    "contribution:edit:own",
    "contribution:submit",
    "contribution:fork",
    "contribution:collaborate",
    "evidence:upload",
    "citation:add",
    "community:vote",
    "community:note",
    "investigation:view",
    "investigation:join",
    "profile:edit:own",
    "profile:view:any",
  ],
  FACT_CHECKER: [
    "contribution:create",
    "contribution:read",
    "contribution:edit:own",
    "contribution:submit",
    "contribution:fork",
    "contribution:collaborate",
    "evidence:upload",
    "citation:add",
    "factcheck:submit",
    "factcheck:review",
    "community:vote",
    "community:note",
    "investigation:view",
    "investigation:join",
    "profile:edit:own",
    "profile:view:any",
  ],
  JOURNALIST: [
    "contribution:create",
    "contribution:read",
    "contribution:edit:own",
    "contribution:submit",
    "contribution:fork",
    "contribution:collaborate",
    "evidence:upload",
    "citation:add",
    "factcheck:submit",
    "factcheck:review",
    "community:vote",
    "community:note",
    "investigation:view",
    "investigation:join",
    "investigation:create",
    "profile:edit:own",
    "profile:view:any",
  ],
  EXPERT_REVIEWER: [
    "contribution:create",
    "contribution:read",
    "contribution:edit:own",
    "contribution:edit:any",
    "contribution:submit",
    "contribution:fork",
    "contribution:collaborate",
    "evidence:upload",
    "citation:add",
    "factcheck:submit",
    "factcheck:review",
    "community:vote",
    "community:note",
    "investigation:view",
    "investigation:join",
    "investigation:create",
    "investigation:lead",
    "profile:edit:own",
    "profile:view:any",
  ],
};

export function hasContributorPermission(
  role: ContributorRole,
  permission: ContributorPermission,
): boolean {
  return (CONTRIBUTOR_PERMISSIONS[role] as readonly ContributorPermission[]).includes(permission);
}

export function canEditContribution(
  role: ContributorRole,
  authorId: string,
  userId: string,
): boolean {
  if (hasContributorPermission(role, "contribution:edit:any")) return true;
  if (hasContributorPermission(role, "contribution:edit:own") && authorId === userId) return true;
  return false;
}
