-- SUPERSEDED — this loose file has been incorporated into the proper
-- migration at 20260530090000_add_vector_search/migration.sql.
-- Do not run this file manually; use `prisma migrate deploy` instead.
